
services:
 mariadb:
    build:
      context: ./requirements/mariadb
    entrypoint: /usr/local/bin/init.sh
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - mariaDB

 wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    restart: always
    networks:
      - wordpress
      - mariaDB
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb

 nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress

networks:
  mariaDB:
    driver: bridge
    internal : true
  wordpress:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
    name: mariadb_data

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
    name: wordpress_data
