
services:
 mariadb:
    build:
      context: ./requirements/mariadb
    entrypoint: /usr/local/bin/init.sh
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception

 wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress

 nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    # depends_on:
    #   wordpress:
    #     condition: service_healthy

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sminot/data/mariadb
    name: mariadb_data
  
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sminot/data/wordpress
    name: wordpress_data
